travis:
  secure:
    BINSTAR_TOKEN: vlkVa4TU1Dcg2afaSg2ZjId1g2pcCtnWkMWhSjTNdK1v05qg1mcHrDR2Gw8yXizh7+B04moztTD6wGBnGy1pUR8ym+QZxyzuulLaL9xtCvKMNb/V69fDm5pPqGmNamfYwNZa1T3dNab+caOuVmekDVAGAhi/W8aQTTVRMNxmCzwKoxsL9EZYS7V7K5w1tV56jdqCB5waVMDHQPFx9tINH8B3/HxpKX/qcFhDPOcK5cxx3kg8muZyJ48C+HWCl/bkzmp9R1c/CPy/+mWp66h/UrzyJQqeH8XkI/+R0l6kn6mdQIB10HmAx7j+sWYf2cNUvZrtwASY9ibtusAeSdJGVJOjRKdG3YZjac+7r0X20ia4WRBvCz9W2uwvN8WP11fQpatsOIbUmGNbJfQ+KYfmivwbfV5ijzbQb7kFP7g001BXD4qCdPZKfT4xMylkjbbBoiapyg3H6rpa0wk/mWOwtRKoi86zt49QB6rFInmgC2zI0NIXmBS15qO+Wkur1QpvViBiOkq+TlkBpSlGz2w53WZPhriPdnEsKrAeKf0U2TYr1T8PZuu1fo3UvpHc6/5t+yymOD66xYYfwu+LlR6qrYYNpqVFXc9Fz0pW96Uw+BcE8kvEOPKnd1EwjiYpSp55t8k1fH81ki94yfxrkeSjQB3Ojs5YMklIMOjLlOSMSR8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
