travis:
  secure:
    BINSTAR_TOKEN: uvjgCQwHtW6V2i3rKDtgNBsg9CLlrjz7o8+7FTLe7to2ra5wP3qR9k7UTMQhLp5beRg3d4De1Pp3J9IRQe2jujDaaOCGZSQISm7lM1VLbfsnVVMwCDV+Kk1PJ5uv5B2oNLkeZfRNxMMEziwXwDuoDYltJJRFU0x4hjJhQs1q/9dAuLemBKNrLrUIywcYxEueX8b79e9a+f8E17a/iIcISJ3hc/+5d+XeE4VlQrksMofE6KY9OvA+l9krwsL99TkWXZtesRMzCpDFLGIVHQUOsngiF9OhO71f10ud0oq7nD09F362jaOnilHGjIojHDZN9Q3eIf7MGLQ4MEGLUV+86wtQS3+uMR11WcPu0034z7FAV/I2gDNtKhDDNcyxIh5SYGzLChoD4qGTPZLfLcWRXhGbjDkwjr1lc0hFl47O34H21jRGd0LASjsirAGOXPG+srbtlapPh2vBNvc1KuuHkE4A51MmFPE8ZVJjEpfIg/KTTJVBduEs1NZtMoB3NoEo/i+hBKHmLXo4e+MxTZ4kYj/wtevQxzHNgjjxUaWr6zsbBZ8u+5+5sYdU8ZKcbUGzuJ0o+icWhSznbZZQjq52g5ANGI8sSs6vtNgGAmISr3FQicfLa3XvkiAKzkpgNRYtUc4ffdBA2b0obGRGwRY338tpv9SWMOk5dSLOORZbEE8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
